### ISSUE TITLE
[BUG] Player plays paused song on rescan

### ISSUE THREAD

**Issue by MayaGeva** [neithern/g4music#77]
If the player is open with a song in paused mode, and a change occurs in the music directory, the player rescans and turns the song back on.

Also if the song is playing during a rescan, the player might switch to a different song (even if nothing had changed with the current song).

**Comment by neithern** [comment]
fixed

**Comment by MayaGeva** [comment]
It's still happening (I'm on version 3.6.2).
If I add or delete files from my music directory, the current song starts playing
